window.tailwind = window.tailwind || {};
window.tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "primary-fixed-dim": "#ffb596",
                "error-container": "#93000a",
                "outline-variant": "#5a4136",
                "secondary-fixed-dim": "#c6c6c7",
                "on-surface": "#e2e2e2",
                "on-error-container": "#ffdad6",
                "secondary": "#c6c6c7",
                "on-primary-fixed": "#360f00",
                "surface-container-high": "#2a2a2a",
                "surface-container-low": "#1b1b1b",
                "surface-tint": "#ffb596",
                "surface-container-highest": "#353535",
                "on-tertiary-container": "#2f2f2f",
                "surface-dim": "#131313",
                "background": "#000000",
                "primary-container": "#ff6600",
                "inverse-surface": "#e2e2e2",
                "on-primary-fixed-variant": "#7c2e00",
                "on-background": "#e2e2e2",
                "on-secondary-fixed": "#1a1c1c",
                "on-secondary-fixed-variant": "#454747",
                "inverse-on-surface": "#303030",
                "on-primary-container": "#000000",
                "outline": "#262626",
                "on-primary": "#581e00",
                "surface": "#000000",
                "primary": "#ff6600",
                "tertiary": "#c8c6c5",
                "on-secondary-container": "#b4b5b5",
                "surface-container-lowest": "#0e0e0e",
                "on-surface-variant": "#e3bfb1",
                "surface-variant": "#262626",
                "surface-container": "#1f1f1f",
                "secondary-container": "#454747",
                "on-secondary": "#2f3131",
                "tertiary-fixed": "#e4e2e1",
                "on-tertiary-fixed-variant": "#474746",
                "inverse-primary": "#a33e00",
                "tertiary-container": "#989696",
                "error": "#ffb4ab",
                "surface-bright": "#393939",
                "on-error": "#690005",
                "secondary-fixed": "#e2e2e2",
                "on-tertiary-fixed": "#1b1c1c",
                "tertiary-fixed-dim": "#c8c6c5",
                "primary-fixed": "#ffdbcd",
                "on-tertiary": "#303030",
            },
            borderRadius: {
                DEFAULT: "0px",
                lg: "0px",
                xl: "0px",
                full: "0px",
            },
            spacing: {
                "stack-md": "1.5rem",
                gutter: "1rem",
                "margin-page": "2rem",
                "stack-sm": "0.5rem",
                "sidebar-width": "288px",
            },
            fontFamily: {
                "body-lg": ["JetBrains Mono"],
                "label-caps": ["JetBrains Mono"],
                "label-mono": ["JetBrains Mono"],
                "headline-md": ["JetBrains Mono"],
                "headline-lg": ["JetBrains Mono"],
                "body-sm": ["JetBrains Mono"],
            },
            fontSize: {
                "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }],
                "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0", fontWeight: "800" }],
                "label-mono": ["11px", { lineHeight: "14px", letterSpacing: "0", fontWeight: "500" }],
                "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "0", fontWeight: "700" }],
                "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "0", fontWeight: "700" }],
                "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "400" }],
            },
        },
    },
};
